== NATS message broker [[nats-messaging]]

WETS clients will react to events generated by the model and signal to the
model when certain milestones occur. To faciliate this communication a simple
messaging broker, a https://nats.io/[NATS server], is employed. This is an
open-source off-the-shelf component that allows multiple entities to publish,
as well as subscribe to, bytestream messages.

The diagram <<wets-message-diagram,below>> shows our `wets-s` service
receiving `Wets.1` messages that it subscribes to, and publishing messages on
`Wets.client`. The client script, `wdriver`, publishes to `Wets.1` and
subscribes to `Wets.client` messages. The `NATS-server` in the middle runs in a
separate process and can handle these as well as other messages for other
clients.
footnote:[During development of a more formal graphical client, it was
convenient to have a tweaked wdriver application running that could deliver
messages to Wets.1 that were still being developed.]

(((NATS,messaging path diagram)))

.WETS messaging path using NATS [[[wets-message-diagram]]]
[pikchr]
----
$margin = 0.4
right; box invis wid 100% ht 50%
arrow <-
M1: box "Wets.1" wid 100% ht 50% fill bisque
arrow <-
box invis wid 100% ht 50%
box same as first box with .t at bottom of first box
arrow ->
M2: box "Wets.client" same as 2nd box
arrow ->
box invis wid 100% ht 50%
// cover the invisible boxes
box "wets-s" with .t at top of first box fill lightblue
box "wdriver" with .t at top of 3rd box fill lightpink
// nats-server box under the message boxes
box ht (M1.n.y-M2.s.y)+$margin wid M1.wid+$margin \
    at M1.s fill 0xe8d8d0 behind M1
"NATS-server" below at 1.33cm south of last box
----

TIP: This section only describes how NATS
is used in this application. Visit the https://nats.io/[NATS.io] site for more
information on downloads and installation.

To use NATS in our application requires,

* A running NATS server (literally, `nats-server`)
* An application that implements the NATS protocol in your chosen
  implementation language.

=== NATS configuration

Prerequisite: https://nats.io/download/[download] a `nats-server` and the NATS
command-line tool for your development environment.

(((NATS,Starting)))
[source,bash]
----
$ nats-server --config=server.conf
----

During development the server configuration is simple and unsecure. If
the port is changed here, it must be changed throughout all other
communication paths.

(((NATS,Configuring)))

.`server.config` file contents
[source,json]
----
websocket {
    port: 8087
    no_tls: true
    authorization {
        username: "test"
        password: "test"
    }
}
----

Now start the wets service. The `info` logging level gives brief but
useful information and tracks the message traffic specific to the NATS
interaction.

[source,bash]
----
$ ./code/wets-s.tcl --level info
[Fri Jan 09 16:41:03 PST 2026] [nats_xfer] [notice] 'Connection status: connected'
[Fri Jan 09 16:41:03 PST 2026] [nats_xfer] [notice] 'NATS version: 2.12.1'
----

If `wets-s` has successfully connected, it is waiting to receive messages from
the nats server. These are expected to be JSON-formatted bytestream messages
containing commands that, if valid, will result in activity within the WETS
translation.

<<wets-s.adoc#wets-s,wets-s>>:: This section contains the code and
documentation for the messages handled by the `wets-s` service.

<<wdriver.adoc#wdriver,wdriver>>:: Is a simple application that uses the
`wets-s` protocol to drive the WETS executable model. It simply replaces the
message sequencing that was originally built into the WETS model for testing.

The eventual target of all this messaging is a web application written in the
`elm` language that uses websockets to communicate with `wets-s`.
