== Project Overview [[project-overview]]

*WETS* is a water elevation transit system, which defines how a
vessel passes through one or more canal locks.
This
https://en.wikipedia.org/wiki/Literate_programming[literate programming document]
defines a communication application that will communicate with a WETS
executable model in an agnostic manner, allowing driver applications to be
written in any language.

Once an information model is translated, it’s public interface is
available to other applications for testing or specific client use. The
water elevation transit system, or WETS, is described in a complete
information model and has been translated to an executable model using
both `rosea` (for `Tcl`) and `micca` (for `C++`).

The goal of the `wets-s` project is to provide a messaging mechanism so that a
simulator, written in any programming language, can be deployed to interact with
the WETS executable model.

Here are the sections of interest if you have already read the details on
literate programming.

[horizontal]
<<nats.adoc#nats-messaging,NATS>>:: How NATS is used in this application.
<<wets-s.adoc#wets-s,wets-s>>:: The server that integrates tightly with the
WETS model and sends and receives NATS messages.
<<wdriver.adoc#wdriver,wdriver>>:: A small `Tcl` script demo showing the use
of the wets-s service to perform a single run of a vessel through the WETS
model.

=== Literate programming

As a https://en.wikipedia.org/wiki/Literate_programming[literate programming document]
the application source code is woven into this document and can be
untangled into working source code as well as the document you are reading.
footnote:[The words, tangle and weave, are established literate programming
terms.] A `Makefile` is provided to build the code and document artifacts so
the detailed mechanism is described there and not in this document.

WARNING: Since the application is generated by this document, fixing
bugs and adding features *must* be done by editing this document.

The `atangle` tool is used for extracting the tangled code. Within
this document you will find code blocks headed with tags that `atangle` will
recognize for organizing the output of the code.

TIP: In this document, final assembly of the code blocks is done in a section
titled _Code Layout_.
